# Generated by Django 5.0.6 on 2024-05-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sap_id', models.IntegerField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
